"""Run an exported graph module across several GPUs.

``get_device_map`` plans the split — it assigns each parameter / buffer to a
device in the order the graph actually uses it, rather than in declaration
order the way ``accelerate`` does.  ``dispatch_model`` applies such a plan, and
``insert_align_device_nodes`` inserts the ``.to(device)`` hops the split graph
needs to stay runnable when an op's operands land on different GPUs.
"""

import logging
from typing import Dict, List

import torch
from accelerate.big_modeling import infer_auto_device_map
from accelerate.utils import get_max_memory
from torch.ao.quantization.fx.utils import assert_and_get_unique_device
from torch.fx import GraphModule, Node
from torch.fx.graph import map_arg

from voyager_compiler.codegen.node_info import dtype_byte_size
from voyager_compiler.codegen.transform.rewrites import deduplicate_nodes
from voyager_compiler.shape_prop import fetch_attr

logger = logging.getLogger(__name__)

__all__ = [
    "dispatch_model",
    "get_device_map",
    "insert_align_device_nodes",
]


def get_device_map(model: GraphModule, max_memory=None, verbose=False):
    """
    The default device map generated by the Hugging Face accelerate library is
    suboptimal because it places all tensors in the order of model parameters,
    children, and buffers, which may not be used in the same order. This
    function generates a device map based on the order of nodes in the graph,
    which reflects the exact order in which tensors are used.
    """
    if max_memory is None:
        max_memory = get_max_memory(max_memory)

    devices = list(max_memory.keys())
    if "disk" not in devices:
        devices.append("disk")

    device_map = {}
    current_device = 0
    current_memory_used = 0

    model.graph.eliminate_dead_code(
        lambda n: n.op in ["placeholder", "output"] or n.is_impure()
    )

    named_modules = dict(model.named_modules(remove_duplicate=True))

    first_use: Dict[Node, int] = {}

    def register_first_use(n: Node, idx: int):
        if n not in first_use:
            first_use[n] = idx

    for i, node in enumerate(model.graph.nodes):
        map_arg(node.args, lambda n: register_first_use(n, i))
        map_arg(node.kwargs, lambda n: register_first_use(n, i))

    nodes_to_treat = [
        n for n in model.graph.nodes if n.op in ["get_attr", "call_module"]
    ]
    nodes_to_treat = sorted(nodes_to_treat, key=lambda n: first_use[n])

    while len(nodes_to_treat) > 0:
        node = nodes_to_treat.pop(0)
        if verbose:
            print(f"\nTreating node {node}.")
        # Assess size needed
        if node.op == "get_attr":
            tensor = fetch_attr(model, node.target)
            if not isinstance(tensor, torch.Tensor):
                continue
            module_size = tensor.numel() * dtype_byte_size(tensor.dtype)
        else:
            module = named_modules[node.target]
            module_size = sum(
                p.numel() * dtype_byte_size(p.dtype)
                for p in module.parameters()
            ) + sum(
                b.numel() * dtype_byte_size(b.dtype) for b in module.buffers()
            )

        device = devices[current_device]
        current_max_size = max_memory[device] if device != "disk" else None

        if (
            current_max_size is not None
            and current_memory_used + module_size > current_max_size
        ):
            if verbose:
                print(
                    f"Not enough space on {devices[current_device]} to "
                    f"put {node} (space available "
                    f"{current_max_size - current_memory_used}, module "
                    f"size {module_size})."
                )
            current_device += 1
            assert current_device < len(
                devices
            ), "Not enough devices to store the model."
            nodes_to_treat = [node] + nodes_to_treat
            current_memory_used = 0
        else:
            if verbose:
                if current_max_size is None:
                    print(
                        f"Putting {node} (size={module_size}) on "
                        f"{devices[current_device]}."
                    )
                else:
                    print(
                        f"Putting {node} (size={module_size}) on "
                        f"{devices[current_device]} (available="
                        f"{current_max_size - current_memory_used})."
                    )
            current_memory_used += module_size
            device_map[node.target] = devices[current_device]

    return device_map


def _normalize_device(device):
    """
    Convert unsupported device_map values such as 'disk' to CPU.
    """
    if isinstance(device, int) and torch.cuda.is_available():
        return torch.device(f"cuda:{device}")

    logger.warning(f"Unsupported device spec {device!r}. Using CPU instead.")
    return torch.device("cpu")


def dispatch_model(model, device_map=None, max_memory=None):
    if device_map is None:
        device_map = infer_auto_device_map(model, max_memory)

    for name, param in model.named_parameters():
        param.data = param.data.to(_normalize_device(device_map[name]))

    for name, child in model.named_children():
        if name in device_map:
            child.to(_normalize_device(device_map[name]))

    for name, buffer in model.named_buffers(recurse=False):
        if name not in device_map:
            logger.warning(f"Buffer {name} not found in device_map, skipping.")
            continue
        buffer.data = buffer.data.to(_normalize_device(device_map[name]))


@torch.no_grad()
def insert_align_device_nodes(model, example_args):
    args_iter = iter(example_args)
    env: Dict[str, Node] = {}
    modules = dict(model.named_modules())

    deduplicate_nodes(model)

    node_to_last_use: Dict[Node, Node] = {}
    user_to_last_uses: Dict[Node, List[Node]] = {}

    def register_last_uses(n: Node, user: Node):
        if n not in node_to_last_use:
            node_to_last_use[n] = user
            user_to_last_uses.setdefault(user, []).append(n)

    for node in reversed(model.graph.nodes):
        map_arg(node.args, lambda n: register_last_uses(n, node))
        map_arg(node.kwargs, lambda n: register_last_uses(n, node))

    def delete_unused_values(user: Node):
        """
        Delete values after their last use. This ensures that values that are
        not used in the remainder of the code are freed and the memory usage
        of the code is optimal.
        """
        nodes_to_delete = user_to_last_uses.get(user, [])
        for n in nodes_to_delete:
            env.pop(n.name, None)

    def load_arg(a):
        return torch.fx.graph.map_arg(a, lambda n: env[n.name])

    def get_unique_device(nodes):
        args = load_arg(nodes)
        devices = {t.device for t in args if isinstance(t, torch.Tensor)}
        non_cpu_devices = [d for d in devices if d.type != "cpu"]
        return non_cpu_devices[-1] if non_cpu_devices else None

    def insert_adaptor(node, user, device):
        value = env[node.name]
        if not isinstance(value, torch.Tensor) or value.device == device:
            return

        to_node = next(
            (
                n
                for n in node.users
                if n.target == torch.Tensor.to and n.args[1] == device
            ),
            None,
        )

        if to_node is None:
            with model.graph.inserting_after(node):
                to_node = model.graph.call_function(
                    torch.Tensor.to, (node, device)
                )

        user.replace_input_with(node, to_node)

        if node_to_last_use[node] == user:
            env.pop(node.name)

        env.setdefault(to_node.name, value.to(device))

        # Update last uses
        node_to_last_use.clear()
        user_to_last_uses.clear()

        for n in reversed(model.graph.nodes):
            map_arg(n.args, lambda arg: register_last_uses(arg, n))
            map_arg(n.kwargs, lambda kwarg: register_last_uses(kwarg, n))

    for node in model.graph.nodes:
        try:
            if node.op == "placeholder":
                result = next(args_iter, None)
            elif node.op == "get_attr":
                result = fetch_attr(model, node.target)
            elif node.op == "call_function":
                device = get_unique_device(node.all_input_nodes)
                if device is not None:
                    for n in node.all_input_nodes:
                        insert_adaptor(n, node, device)
                result = node.target(
                    *load_arg(node.args), **load_arg(node.kwargs)
                )
            elif node.op == "call_module":
                module = modules[node.target]
                device = assert_and_get_unique_device(module)
                for n in node.all_input_nodes:
                    insert_adaptor(n, node, device)
                result = modules[node.target](
                    *load_arg(node.args), **load_arg(node.kwargs)
                )
        except:
            print(
                f"Error processing node {node} of type {node.op} "
                f"with target {node.target}"
            )
            raise

        env[node.name] = result
        delete_unused_values(node)

    model.graph.lint()
    model.recompile()
