"""ATen compute / elementwise classifiers.

GENERATED FILE -- DO NOT EDIT MANUALLY.  Regenerate with::

    python tools/gen_aten_classifier.py

An op is **compute** when its Core ATen decomposition performs arithmetic
anywhere, and **elementwise** when all of that arithmetic is elementwise and
the rest of the decomposition only reshapes, broadcasts or materializes
constants.  Elementwise is a subset of compute.

Generated:              2026-07-10T10:14:10+00:00
Torch version:          2.12.1+cu126
Model corpus size:      250
  Hugging Face count:   200
  timm count:           50
  exported models:      222
  failed models:        28
Unique ATen ops seen:   144
Classified compute:     251
Classified elementwise: 180
"""

import functools

import torch
from torch.fx import Node

# --- BEGIN GENERATED ATEN CLASSIFIER ---
_GENERATED_COMPUTE_OPS = (
    torch.ops.aten.__and__.Tensor,
    torch.ops.aten.__or__.Tensor,
    torch.ops.aten._adaptive_avg_pool2d.default,
    torch.ops.aten._adaptive_avg_pool2d_backward.default,
    torch.ops.aten._adaptive_avg_pool3d.default,
    torch.ops.aten._cdist_forward.default,
    torch.ops.aten._embedding_bag.default,
    torch.ops.aten._fft_c2r.default,
    torch.ops.aten._fft_r2c.default,
    torch.ops.aten._log_softmax.default,
    torch.ops.aten._native_batch_norm_legit.default,
    torch.ops.aten._native_batch_norm_legit.no_stats,
    torch.ops.aten._native_batch_norm_legit_no_training.default,
    torch.ops.aten._pdist_forward.default,
    torch.ops.aten._softmax.default,
    torch.ops.aten.abs.default,
    torch.ops.aten.abs_.default,
    torch.ops.aten.acos.default,
    torch.ops.aten.acos_.default,
    torch.ops.aten.acosh.default,
    torch.ops.aten.acosh_.default,
    torch.ops.aten.adaptive_avg_pool1d.default,
    torch.ops.aten.adaptive_avg_pool2d.default,
    torch.ops.aten.add.Scalar,
    torch.ops.aten.add.Tensor,
    torch.ops.aten.add_.Scalar,
    torch.ops.aten.add_.Tensor,
    torch.ops.aten.addmm.default,
    torch.ops.aten.addmm_.default,
    torch.ops.aten.amax.default,
    torch.ops.aten.amin.default,
    torch.ops.aten.any.default,
    torch.ops.aten.any.dim,
    torch.ops.aten.any.dims,
    torch.ops.aten.argmax.default,
    torch.ops.aten.argmin.default,
    torch.ops.aten.asin.default,
    torch.ops.aten.asin_.default,
    torch.ops.aten.asinh.default,
    torch.ops.aten.asinh_.default,
    torch.ops.aten.atan.default,
    torch.ops.aten.atan2.default,
    torch.ops.aten.atan2.out,
    torch.ops.aten.atan2_.default,
    torch.ops.aten.atan_.default,
    torch.ops.aten.atanh.default,
    torch.ops.aten.atanh_.default,
    torch.ops.aten.avg_pool1d.default,
    torch.ops.aten.avg_pool2d.default,
    torch.ops.aten.avg_pool2d_backward.default,
    torch.ops.aten.avg_pool3d.default,
    torch.ops.aten.batch_norm.default,
    torch.ops.aten.bitwise_and.Scalar,
    torch.ops.aten.bitwise_and.Tensor,
    torch.ops.aten.bitwise_and_.Scalar,
    torch.ops.aten.bitwise_and_.Tensor,
    torch.ops.aten.bitwise_not.default,
    torch.ops.aten.bitwise_not_.default,
    torch.ops.aten.bitwise_or.Scalar,
    torch.ops.aten.bitwise_or.Tensor,
    torch.ops.aten.bitwise_or_.Scalar,
    torch.ops.aten.bitwise_or_.Tensor,
    torch.ops.aten.bitwise_xor.Scalar,
    torch.ops.aten.bitwise_xor.Tensor,
    torch.ops.aten.bitwise_xor_.Scalar,
    torch.ops.aten.bitwise_xor_.Tensor,
    torch.ops.aten.bmm.default,
    torch.ops.aten.ceil.default,
    torch.ops.aten.ceil_.default,
    torch.ops.aten.clamp.Tensor,
    torch.ops.aten.clamp.default,
    torch.ops.aten.clamp_.Tensor,
    torch.ops.aten.clamp_.default,
    torch.ops.aten.clamp_min.default,
    torch.ops.aten.clamp_min_.default,
    torch.ops.aten.conv1d.default,
    torch.ops.aten.conv2d.default,
    torch.ops.aten.convolution.default,
    torch.ops.aten.convolution_backward.default,
    torch.ops.aten.cos.default,
    torch.ops.aten.cos_.default,
    torch.ops.aten.cosh.default,
    torch.ops.aten.cosh_.default,
    torch.ops.aten.cumsum.default,
    torch.ops.aten.cumsum_.default,
    torch.ops.aten.div.Scalar,
    torch.ops.aten.div.Scalar_mode,
    torch.ops.aten.div.Tensor,
    torch.ops.aten.div.Tensor_mode,
    torch.ops.aten.div_.Scalar,
    torch.ops.aten.div_.Scalar_mode,
    torch.ops.aten.div_.Tensor,
    torch.ops.aten.div_.Tensor_mode,
    torch.ops.aten.elu.default,
    torch.ops.aten.elu_.default,
    torch.ops.aten.embedding_dense_backward.default,
    torch.ops.aten.eq.Scalar,
    torch.ops.aten.eq.Tensor,
    torch.ops.aten.eq_.Scalar,
    torch.ops.aten.eq_.Tensor,
    torch.ops.aten.erf.default,
    torch.ops.aten.erf_.default,
    torch.ops.aten.exp.default,
    torch.ops.aten.exp_.default,
    torch.ops.aten.expm1.default,
    torch.ops.aten.expm1_.default,
    torch.ops.aten.floor.default,
    torch.ops.aten.floor_.default,
    torch.ops.aten.floor_divide.default,
    torch.ops.aten.fmod.Scalar,
    torch.ops.aten.fmod.Tensor,
    torch.ops.aten.fmod_.Scalar,
    torch.ops.aten.fmod_.Tensor,
    torch.ops.aten.ge.Scalar,
    torch.ops.aten.ge.Tensor,
    torch.ops.aten.ge_.Scalar,
    torch.ops.aten.ge_.Tensor,
    torch.ops.aten.gelu.default,
    torch.ops.aten.gelu_.default,
    torch.ops.aten.grid_sampler_2d.default,
    torch.ops.aten.group_norm.default,
    torch.ops.aten.gt.Scalar,
    torch.ops.aten.gt.Tensor,
    torch.ops.aten.gt_.Scalar,
    torch.ops.aten.gt_.Tensor,
    torch.ops.aten.hardsigmoid.default,
    torch.ops.aten.hardsigmoid_.default,
    torch.ops.aten.hardswish.default,
    torch.ops.aten.hardswish_.default,
    torch.ops.aten.hardtanh.default,
    torch.ops.aten.hardtanh_.default,
    torch.ops.aten.isinf.default,
    torch.ops.aten.isnan.default,
    torch.ops.aten.layer_norm.default,
    torch.ops.aten.le.Scalar,
    torch.ops.aten.le.Tensor,
    torch.ops.aten.le_.Scalar,
    torch.ops.aten.le_.Tensor,
    torch.ops.aten.leaky_relu.default,
    torch.ops.aten.leaky_relu_.default,
    torch.ops.aten.linear.default,
    torch.ops.aten.log.default,
    torch.ops.aten.log10.default,
    torch.ops.aten.log10_.default,
    torch.ops.aten.log1p.default,
    torch.ops.aten.log1p_.default,
    torch.ops.aten.log2.default,
    torch.ops.aten.log2_.default,
    torch.ops.aten.log_.default,
    torch.ops.aten.logical_and.default,
    torch.ops.aten.logical_and_.default,
    torch.ops.aten.logical_not.default,
    torch.ops.aten.logical_not_.default,
    torch.ops.aten.logical_or.default,
    torch.ops.aten.logical_or_.default,
    torch.ops.aten.logical_xor.default,
    torch.ops.aten.logical_xor_.default,
    torch.ops.aten.lt.Scalar,
    torch.ops.aten.lt.Tensor,
    torch.ops.aten.lt_.Scalar,
    torch.ops.aten.lt_.Tensor,
    torch.ops.aten.masked_fill.Scalar,
    torch.ops.aten.masked_fill_.Scalar,
    torch.ops.aten.matmul.default,
    torch.ops.aten.max.dim,
    torch.ops.aten.max_pool2d.default,
    torch.ops.aten.max_pool2d_with_indices.default,
    torch.ops.aten.max_pool2d_with_indices_backward.default,
    torch.ops.aten.max_pool3d_with_indices.default,
    torch.ops.aten.maximum.default,
    torch.ops.aten.mean.default,
    torch.ops.aten.mean.dim,
    torch.ops.aten.min.dim,
    torch.ops.aten.min.other,
    torch.ops.aten.minimum.default,
    torch.ops.aten.mm.default,
    torch.ops.aten.mul.Scalar,
    torch.ops.aten.mul.Tensor,
    torch.ops.aten.mul_.Scalar,
    torch.ops.aten.mul_.Tensor,
    torch.ops.aten.native_group_norm.default,
    torch.ops.aten.native_group_norm_backward.default,
    torch.ops.aten.native_layer_norm.default,
    torch.ops.aten.native_layer_norm_backward.default,
    torch.ops.aten.ne.Scalar,
    torch.ops.aten.ne.Tensor,
    torch.ops.aten.ne_.Scalar,
    torch.ops.aten.ne_.Tensor,
    torch.ops.aten.neg.default,
    torch.ops.aten.neg_.default,
    torch.ops.aten.pow.Scalar,
    torch.ops.aten.pow.Tensor_Scalar,
    torch.ops.aten.pow.Tensor_Tensor,
    torch.ops.aten.pow_.Scalar,
    torch.ops.aten.prod.default,
    torch.ops.aten.prod.dim_int,
    torch.ops.aten.reciprocal.default,
    torch.ops.aten.reciprocal_.default,
    torch.ops.aten.relu.default,
    torch.ops.aten.relu_.default,
    torch.ops.aten.remainder.Scalar,
    torch.ops.aten.remainder.Tensor,
    torch.ops.aten.remainder_.Scalar,
    torch.ops.aten.remainder_.Tensor,
    torch.ops.aten.roll.default,
    torch.ops.aten.round.default,
    torch.ops.aten.round_.default,
    torch.ops.aten.rsqrt.default,
    torch.ops.aten.rsqrt_.default,
    torch.ops.aten.rsub.Scalar,
    torch.ops.aten.scaled_dot_product_attention.default,
    torch.ops.aten.sigmoid.default,
    torch.ops.aten.sigmoid_.default,
    torch.ops.aten.sign.default,
    torch.ops.aten.sign_.default,
    torch.ops.aten.silu.default,
    torch.ops.aten.silu_.default,
    torch.ops.aten.sin.default,
    torch.ops.aten.sin_.default,
    torch.ops.aten.sinh.default,
    torch.ops.aten.sinh_.default,
    torch.ops.aten.softmax.int,
    torch.ops.aten.softplus.default,
    torch.ops.aten.sort.default,
    torch.ops.aten.sqrt.default,
    torch.ops.aten.sqrt_.default,
    torch.ops.aten.square.default,
    torch.ops.aten.square_.default,
    torch.ops.aten.sub.Scalar,
    torch.ops.aten.sub.Tensor,
    torch.ops.aten.sub_.Scalar,
    torch.ops.aten.sub_.Tensor,
    torch.ops.aten.sum.dim_IntList,
    torch.ops.aten.tan.default,
    torch.ops.aten.tan_.default,
    torch.ops.aten.tanh.default,
    torch.ops.aten.tanh_.default,
    torch.ops.aten.topk.default,
    torch.ops.aten.tril.default,
    torch.ops.aten.tril_.default,
    torch.ops.aten.triu.default,
    torch.ops.aten.triu_.default,
    torch.ops.aten.trunc.default,
    torch.ops.aten.trunc_.default,
    torch.ops.aten.upsample_bicubic2d.vec,
    torch.ops.aten.upsample_bilinear2d.vec,
    torch.ops.aten.var.correction,
    torch.ops.aten.var.dim,
    torch.ops.aten.where.ScalarOther,
    torch.ops.aten.where.ScalarSelf,
    torch.ops.aten.where.self,
)

_GENERATED_ELEMENTWISE_OPS = (
    torch.ops.aten.__and__.Tensor,
    torch.ops.aten.__or__.Tensor,
    torch.ops.aten.abs.default,
    torch.ops.aten.abs_.default,
    torch.ops.aten.acos.default,
    torch.ops.aten.acos_.default,
    torch.ops.aten.acosh.default,
    torch.ops.aten.acosh_.default,
    torch.ops.aten.add.Scalar,
    torch.ops.aten.add.Tensor,
    torch.ops.aten.add_.Scalar,
    torch.ops.aten.add_.Tensor,
    torch.ops.aten.asin.default,
    torch.ops.aten.asin_.default,
    torch.ops.aten.asinh.default,
    torch.ops.aten.asinh_.default,
    torch.ops.aten.atan.default,
    torch.ops.aten.atan2.default,
    torch.ops.aten.atan2.out,
    torch.ops.aten.atan2_.default,
    torch.ops.aten.atan_.default,
    torch.ops.aten.atanh.default,
    torch.ops.aten.atanh_.default,
    torch.ops.aten.bitwise_and.Scalar,
    torch.ops.aten.bitwise_and.Tensor,
    torch.ops.aten.bitwise_and_.Scalar,
    torch.ops.aten.bitwise_and_.Tensor,
    torch.ops.aten.bitwise_not.default,
    torch.ops.aten.bitwise_not_.default,
    torch.ops.aten.bitwise_or.Scalar,
    torch.ops.aten.bitwise_or.Tensor,
    torch.ops.aten.bitwise_or_.Scalar,
    torch.ops.aten.bitwise_or_.Tensor,
    torch.ops.aten.bitwise_xor.Scalar,
    torch.ops.aten.bitwise_xor.Tensor,
    torch.ops.aten.bitwise_xor_.Scalar,
    torch.ops.aten.bitwise_xor_.Tensor,
    torch.ops.aten.ceil.default,
    torch.ops.aten.ceil_.default,
    torch.ops.aten.clamp.Tensor,
    torch.ops.aten.clamp.default,
    torch.ops.aten.clamp_.Tensor,
    torch.ops.aten.clamp_.default,
    torch.ops.aten.clamp_min.default,
    torch.ops.aten.clamp_min_.default,
    torch.ops.aten.cos.default,
    torch.ops.aten.cos_.default,
    torch.ops.aten.cosh.default,
    torch.ops.aten.cosh_.default,
    torch.ops.aten.div.Scalar,
    torch.ops.aten.div.Scalar_mode,
    torch.ops.aten.div.Tensor,
    torch.ops.aten.div.Tensor_mode,
    torch.ops.aten.div_.Scalar,
    torch.ops.aten.div_.Scalar_mode,
    torch.ops.aten.div_.Tensor,
    torch.ops.aten.div_.Tensor_mode,
    torch.ops.aten.elu.default,
    torch.ops.aten.elu_.default,
    torch.ops.aten.eq.Scalar,
    torch.ops.aten.eq.Tensor,
    torch.ops.aten.eq_.Scalar,
    torch.ops.aten.eq_.Tensor,
    torch.ops.aten.erf.default,
    torch.ops.aten.erf_.default,
    torch.ops.aten.exp.default,
    torch.ops.aten.exp_.default,
    torch.ops.aten.expm1.default,
    torch.ops.aten.expm1_.default,
    torch.ops.aten.floor.default,
    torch.ops.aten.floor_.default,
    torch.ops.aten.floor_divide.default,
    torch.ops.aten.fmod.Scalar,
    torch.ops.aten.fmod.Tensor,
    torch.ops.aten.fmod_.Scalar,
    torch.ops.aten.fmod_.Tensor,
    torch.ops.aten.ge.Scalar,
    torch.ops.aten.ge.Tensor,
    torch.ops.aten.ge_.Scalar,
    torch.ops.aten.ge_.Tensor,
    torch.ops.aten.gelu.default,
    torch.ops.aten.gelu_.default,
    torch.ops.aten.gt.Scalar,
    torch.ops.aten.gt.Tensor,
    torch.ops.aten.gt_.Scalar,
    torch.ops.aten.gt_.Tensor,
    torch.ops.aten.hardsigmoid.default,
    torch.ops.aten.hardsigmoid_.default,
    torch.ops.aten.hardswish.default,
    torch.ops.aten.hardswish_.default,
    torch.ops.aten.hardtanh.default,
    torch.ops.aten.hardtanh_.default,
    torch.ops.aten.isinf.default,
    torch.ops.aten.isnan.default,
    torch.ops.aten.le.Scalar,
    torch.ops.aten.le.Tensor,
    torch.ops.aten.le_.Scalar,
    torch.ops.aten.le_.Tensor,
    torch.ops.aten.leaky_relu.default,
    torch.ops.aten.leaky_relu_.default,
    torch.ops.aten.log.default,
    torch.ops.aten.log10.default,
    torch.ops.aten.log10_.default,
    torch.ops.aten.log1p.default,
    torch.ops.aten.log1p_.default,
    torch.ops.aten.log2.default,
    torch.ops.aten.log2_.default,
    torch.ops.aten.log_.default,
    torch.ops.aten.logical_and.default,
    torch.ops.aten.logical_and_.default,
    torch.ops.aten.logical_not.default,
    torch.ops.aten.logical_not_.default,
    torch.ops.aten.logical_or.default,
    torch.ops.aten.logical_or_.default,
    torch.ops.aten.logical_xor.default,
    torch.ops.aten.logical_xor_.default,
    torch.ops.aten.lt.Scalar,
    torch.ops.aten.lt.Tensor,
    torch.ops.aten.lt_.Scalar,
    torch.ops.aten.lt_.Tensor,
    torch.ops.aten.masked_fill.Scalar,
    torch.ops.aten.masked_fill_.Scalar,
    torch.ops.aten.maximum.default,
    torch.ops.aten.min.other,
    torch.ops.aten.minimum.default,
    torch.ops.aten.mul.Scalar,
    torch.ops.aten.mul.Tensor,
    torch.ops.aten.mul_.Scalar,
    torch.ops.aten.mul_.Tensor,
    torch.ops.aten.ne.Scalar,
    torch.ops.aten.ne.Tensor,
    torch.ops.aten.ne_.Scalar,
    torch.ops.aten.ne_.Tensor,
    torch.ops.aten.neg.default,
    torch.ops.aten.neg_.default,
    torch.ops.aten.pow.Scalar,
    torch.ops.aten.pow.Tensor_Scalar,
    torch.ops.aten.pow.Tensor_Tensor,
    torch.ops.aten.pow_.Scalar,
    torch.ops.aten.reciprocal.default,
    torch.ops.aten.reciprocal_.default,
    torch.ops.aten.relu.default,
    torch.ops.aten.relu_.default,
    torch.ops.aten.remainder.Scalar,
    torch.ops.aten.remainder.Tensor,
    torch.ops.aten.remainder_.Scalar,
    torch.ops.aten.remainder_.Tensor,
    torch.ops.aten.round.default,
    torch.ops.aten.round_.default,
    torch.ops.aten.rsqrt.default,
    torch.ops.aten.rsqrt_.default,
    torch.ops.aten.rsub.Scalar,
    torch.ops.aten.sigmoid.default,
    torch.ops.aten.sigmoid_.default,
    torch.ops.aten.sign.default,
    torch.ops.aten.sign_.default,
    torch.ops.aten.silu.default,
    torch.ops.aten.silu_.default,
    torch.ops.aten.sin.default,
    torch.ops.aten.sin_.default,
    torch.ops.aten.sinh.default,
    torch.ops.aten.sinh_.default,
    torch.ops.aten.softplus.default,
    torch.ops.aten.sqrt.default,
    torch.ops.aten.sqrt_.default,
    torch.ops.aten.square.default,
    torch.ops.aten.square_.default,
    torch.ops.aten.sub.Scalar,
    torch.ops.aten.sub.Tensor,
    torch.ops.aten.sub_.Scalar,
    torch.ops.aten.sub_.Tensor,
    torch.ops.aten.tan.default,
    torch.ops.aten.tan_.default,
    torch.ops.aten.tanh.default,
    torch.ops.aten.tanh_.default,
    torch.ops.aten.trunc.default,
    torch.ops.aten.trunc_.default,
    torch.ops.aten.where.ScalarOther,
    torch.ops.aten.where.ScalarSelf,
    torch.ops.aten.where.self,
)
# --- END GENERATED ATEN CLASSIFIER ---

# Hand-maintained.  ``quantized_ops`` are CompositeExplicitAutograd custom ops
# with no decomposition -- they survive ``run_decompositions`` unchanged, so the
# generator cannot classify them and never tries to.
_QUANTIZED_COMPUTE_OPS = (
    "_adaptive_avg_pool2d",
    "adaptive_avg_pool2d",
    "avg_pool2d",
    "conv2d",
    "conv2d_mx",
    "dequantize",
    "layer_norm",
    "linear",
    "linear_mx",
    "matmul",
    "matmul_mx",
    "max_pool2d",
    "quantize",
    "quantize_mx",
    "quantize_mx_outlier",
    "spmm_csr",
    "vmap",
)

_QUANTIZED_ELEMENTWISE_OPS = ("dequantize", "quantize", "vmap")


def _quantized(names):
    """Resolve ``quantized_ops`` targets, skipping any not yet registered."""
    ops = set()
    for name in names:
        packet = getattr(torch.ops.quantized_ops, name, None)
        if packet is not None:
            ops.add(packet.default)
    return ops


# The custom ops register on package import, after this module is first read,
# so both unions are built on first predicate call rather than at import time.
@functools.cache
def _compute_ops() -> frozenset:
    return frozenset(_GENERATED_COMPUTE_OPS) | _quantized(
        _QUANTIZED_COMPUTE_OPS
    )


@functools.cache
def _elementwise_ops() -> frozenset:
    return frozenset(_GENERATED_ELEMENTWISE_OPS) | _quantized(
        _QUANTIZED_ELEMENTWISE_OPS
    )


def is_compute_op(node: Node) -> bool:
    """Whether ``node`` performs arithmetic -- a kernel, not data movement."""
    return node.target in _compute_ops()


def is_elementwise_op(node: Node) -> bool:
    """Whether ``node`` maps one output element per input element."""
    return node.target in _elementwise_ops()
