# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tiling.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'tiling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctiling.proto\x12\x07voyager\"7\n\tLoopBound\x12\x1b\n\x04loop\x18\x01 \x01(\x0e\x32\r.voyager.Loop\x12\r\n\x05\x62ound\x18\x02 \x01(\x05\"6\n\x0bLevelTiling\x12\'\n\x0bloop_bounds\x18\x01 \x03(\x0b\x32\x12.voyager.LoopBound\"h\n\x10LevelAccessCount\x12\x1a\n\x12input_access_count\x18\x01 \x01(\x04\x12\x1b\n\x13output_access_count\x18\x02 \x01(\x04\x12\x1b\n\x13weight_access_count\x18\x03 \x01(\x04\"\xae\x01\n\x06Tiling\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\rlevel_tilings\x18\x02 \x03(\x0b\x32\x14.voyager.LevelTiling\x12\x36\n\x13level_access_counts\x18\x03 \x03(\x0b\x32\x19.voyager.LevelAccessCount\x12\x18\n\x10logical_channels\x18\x04 \x03(\x05\x12\x17\n\x0fpadded_channels\x18\x05 \x03(\x05\"j\n\x0bModelTiling\x12 \n\x07tilings\x18\x01 \x03(\x0b\x32\x0f.voyager.Tiling\x12\x0f\n\x07\x62\x61\x63kend\x18\x02 \x01(\t\x12\x1c\n\x14target_configuration\x18\x05 \x01(\tJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05*>\n\x04Loop\x12\x06\n\x02\x46X\x10\x00\x12\x06\n\x02\x46Y\x10\x01\x12\x06\n\x02OX\x10\x02\x12\x06\n\x02OY\x10\x03\x12\x06\n\x02OC\x10\x04\x12\x06\n\x02IC\x10\x05\x12\x06\n\x02ON\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tiling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOP']._serialized_start=529
  _globals['_LOOP']._serialized_end=591
  _globals['_LOOPBOUND']._serialized_start=25
  _globals['_LOOPBOUND']._serialized_end=80
  _globals['_LEVELTILING']._serialized_start=82
  _globals['_LEVELTILING']._serialized_end=136
  _globals['_LEVELACCESSCOUNT']._serialized_start=138
  _globals['_LEVELACCESSCOUNT']._serialized_end=242
  _globals['_TILING']._serialized_start=245
  _globals['_TILING']._serialized_end=419
  _globals['_MODELTILING']._serialized_start=421
  _globals['_MODELTILING']._serialized_end=527
# @@protoc_insertion_point(module_scope)
